### ISSUE TITLE
Can not find 'data/causal_data.csv'

### ISSUE THREAD

**Issue by Jun-jie-Huang** [AndreasOpedal/slangvolution#1]
Dear authors, thanks for your nice repo. I try to run your code, but I didn't find the data `data/causal_data.csv` for causal discovery. So could you tell me where can I find the file?

Thanks!

**Comment by Daphiy** [comment]
Dear Jun-jie-Huang,

Thanks for the interest in our work, I'm attaching the causal data used for
our analysis.

Best,
Daphna
